const products = [
    {
        "Unique_ID": 1,
        "ProductID": 1,
        "ProductName": "Chai",
        "SupplierID": 1,
        "CategoryID": 1,
        "QuantityPerUnit": "10 boxes x 20 bags",
        "UnitPrice": 23.1,
        "UnitsInStock": 0,
        "UnitsOnOrder": null,
        "ReorderLevel": 10,
        "Discontinued": false
    },
    {
        "Unique_ID": 2,
        "ProductID": 2,
        "ProductName": "Chang",
        "SupplierID": 1,
        "CategoryID": 5,
        "QuantityPerUnit": "24 - 12 oz bottles",
        "UnitPrice": 29.26,
        "UnitsInStock": 0,
        "UnitsOnOrder": null,
        "ReorderLevel": 25,
        "Discontinued": false
    },
    {
        "Unique_ID": 3,
        "ProductID": 3,
        "ProductName": "Aniseed Syrup",
        "SupplierID": 3,
        "CategoryID": 1,
        "QuantityPerUnit": "12 - 550 ml bottles",
        "UnitPrice": 14.5,
        "UnitsInStock": 0,
        "UnitsOnOrder": 70,
        "ReorderLevel": 25,
        "Discontinued": false
    },
    {
        "Unique_ID": 4,
        "ProductID": 4,
        "ProductName": "Chef Anton's Cajun Seasoning",
        "SupplierID": 2,
        "CategoryID": 2,
        "QuantityPerUnit": "48 - 6 oz jars",
        "UnitPrice": 29.7,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": false
    },
    {
        "Unique_ID": 5,
        "ProductID": 5,
        "ProductName": "Chef Anton-s Gumbo Mix - sdfg",
        "SupplierID": 2,
        "CategoryID": 2,
        "QuantityPerUnit": "36 boxes",
        "UnitPrice": 24.695,
        "UnitsInStock": 0,
        "UnitsOnOrder": 50,
        "ReorderLevel": 0,
        "Discontinued": true
    },
    {
        "Unique_ID": 6,
        "ProductID": 6,
        "ProductName": "Grandma's Boysenberry Spread",
        "SupplierID": 3,
        "CategoryID": 3,
        "QuantityPerUnit": "12 - 8 oz jars",
        "UnitPrice": 27.5,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 25,
        "Discontinued": false
    },
    {
        "Unique_ID": 7,
        "ProductID": 7,
        "ProductName": "Uncle Bob's Organic Dried Pears",
        "SupplierID": 2,
        "CategoryID": 3,
        "QuantityPerUnit": "12 - 1 lb pkgs.",
        "UnitPrice": 39.6,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 10,
        "Discontinued": false
    },
    {
        "Unique_ID": 8,
        "ProductID": 8,
        "ProductName": "Northwoods Cranberry Sauce",
        "SupplierID": 2,
        "CategoryID": 3,
        "QuantityPerUnit": "12 - 12 oz jars",
        "UnitPrice": 49.5,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": true
    },
    {
        "Unique_ID": 9,
        "ProductID": 9,
        "ProductName": "Mishi Kobe Niku",
        "SupplierID": 6,
        "CategoryID": 4,
        "QuantityPerUnit": "18 - 500 g pkgs.",
        "UnitPrice": 12.1,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": true
    },
    {
        "Unique_ID": 10,
        "ProductID": 10,
        "ProductName": "Ikura",
        "SupplierID": 8,
        "CategoryID": 4,
        "QuantityPerUnit": "12 - 200 ml jars.",
        "UnitPrice": 110,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": false
    },
    {
        "Unique_ID": 11,
        "ProductID": 11,
        "ProductName": "Queso Cabrales",
        "SupplierID": 4,
        "CategoryID": 5,
        "QuantityPerUnit": "1 kg pkg.",
        "UnitPrice": 23.1,
        "UnitsInStock": 0,
        "UnitsOnOrder": 30,
        "ReorderLevel": 30,
        "Discontinued": false
    },
    {
        "Unique_ID": 12,
        "ProductID": 12,
        "ProductName": "Queso Manchego La Pastora",
        "SupplierID": 4,
        "CategoryID": 5,
        "QuantityPerUnit": "10 - 500 g pkgs.",
        "UnitPrice": 41.8,
        "UnitsInStock": 5,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": false
    },
    {
        "Unique_ID": 13,
        "ProductID": 13,
        "ProductName": "Konbu",
        "SupplierID": 8,
        "CategoryID": 6,
        "QuantityPerUnit": "2 kg box",
        "UnitPrice": 6.6,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 45,
        "Discontinued": false
    },
    {
        "Unique_ID": 14,
        "ProductID": 14,
        "ProductName": "Tofu - lsdkflskd",
        "SupplierID": 7,
        "CategoryID": 6,
        "QuantityPerUnit": "40 - 100 g pkgs.",
        "UnitPrice": 25.575,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": false
    },
    {
        "Unique_ID": 15,
        "ProductID": 15,
        "ProductName": "Genen Shouyu",
        "SupplierID": 2,
        "CategoryID": 6,
        "QuantityPerUnit": "24 - 250 ml bottles",
        "UnitPrice": 17.05,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 5,
        "Discontinued": false
    },
    {
        "Unique_ID": 16,
        "ProductID": 16,
        "ProductName": "Pavlova",
        "SupplierID": 3,
        "CategoryID": 7,
        "QuantityPerUnit": "32 - 500 g boxes",
        "UnitPrice": 19.195,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 10,
        "Discontinued": false
    },
    {
        "Unique_ID": 17,
        "ProductID": 17,
        "ProductName": "Alice Mutton",
        "SupplierID": 6,
        "CategoryID": 7,
        "QuantityPerUnit": "20 - 1 kg tins",
        "UnitPrice": 42.9,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": true
    },
    {
        "Unique_ID": 18,
        "ProductID": 18,
        "ProductName": "Carnarvon Tigers",
        "SupplierID": 8,
        "CategoryID": 7,
        "QuantityPerUnit": "16 kg pkg.",
        "UnitPrice": 68.75,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": false
    },
    {
        "Unique_ID": 19,
        "ProductID": 19,
        "ProductName": "Teatime Chocolate Biscuits",
        "SupplierID": 3,
        "CategoryID": 3,
        "QuantityPerUnit": "10 boxes x 12 pieces",
        "UnitPrice": 10.12,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 5,
        "Discontinued": false
    },
    {
        "Unique_ID": 20,
        "ProductID": 20,
        "ProductName": "Sir Rodney's Marmalade",
        "SupplierID": 3,
        "CategoryID": 8,
        "QuantityPerUnit": "30 gift boxes",
        "UnitPrice": 89.1,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": false
    },
    {
        "Unique_ID": 21,
        "ProductID": 21,
        "ProductName": "Sir Rodney's Scones",
        "SupplierID": 3,
        "CategoryID": 8,
        "QuantityPerUnit": "24 pkgs. x 2 pieces",
        "UnitPrice": 12.1,
        "UnitsInStock": 0,
        "UnitsOnOrder": 40,
        "ReorderLevel": 5,
        "Discontinued": false
    },
    {
        "Unique_ID": 22,
        "ProductID": 22,
        "ProductName": "Gustaf's Knäckebröd",
        "SupplierID": 9,
        "CategoryID": 5,
        "QuantityPerUnit": "24 - 500 g pkgs.",
        "UnitPrice": 25.41,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 25,
        "Discontinued": false
    },
    {
        "Unique_ID": 23,
        "ProductID": 23,
        "ProductName": "Tunnbröd",
        "SupplierID": 9,
        "CategoryID": 5,
        "QuantityPerUnit": "12 - 250 g pkgs.",
        "UnitPrice": 53.6393,
        "UnitsInStock": 1,
        "UnitsOnOrder": 0,
        "ReorderLevel": 25,
        "Discontinued": false
    },
    {
        "Unique_ID": 24,
        "ProductID": 24,
        "ProductName": "Guaraná Fantástica",
        "SupplierID": 10,
        "CategoryID": 1,
        "QuantityPerUnit": "12 - 355 ml cans",
        "UnitPrice": 5.445,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": true
    },
    {
        "Unique_ID": 25,
        "ProductID": 25,
        "ProductName": "NuNuCa Nuß-Nougat-Creme",
        "SupplierID": 11,
        "CategoryID": 3,
        "QuantityPerUnit": "20 - 450 g glasses",
        "UnitPrice": 16.94,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 30,
        "Discontinued": false
    },
    {
        "Unique_ID": 26,
        "ProductID": 26,
        "ProductName": "Gumbär Gummibärchen",
        "SupplierID": 11,
        "CategoryID": 3,
        "QuantityPerUnit": "100 - 250 g bags",
        "UnitPrice": 37.7883,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": false
    },
    {
        "Unique_ID": 27,
        "ProductID": 27,
        "ProductName": "Schoggi Schokolade",
        "SupplierID": 11,
        "CategoryID": 3,
        "QuantityPerUnit": "100 - 100 g pieces",
        "UnitPrice": 53.119,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 30,
        "Discontinued": false
    },
    {
        "Unique_ID": 28,
        "ProductID": 28,
        "ProductName": "Rössle Sauerkraut",
        "SupplierID": 12,
        "CategoryID": 7,
        "QuantityPerUnit": "25 - 825 g cans",
        "UnitPrice": 55.176,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": true
    },
    {
        "Unique_ID": 29,
        "ProductID": 29,
        "ProductName": "Thüringer Rostbratwurst",
        "SupplierID": 12,
        "CategoryID": 6,
        "QuantityPerUnit": "50 bags x 30 sausgs.",
        "UnitPrice": 149.7859,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 0,
        "Discontinued": true
    },
    {
        "Unique_ID": 30,
        "ProductID": 30,
        "ProductName": "Nord-Ost Matjeshering",
        "SupplierID": 13,
        "CategoryID": 8,
        "QuantityPerUnit": "10 - 200 g glasses",
        "UnitPrice": 31.3269,
        "UnitsInStock": 0,
        "UnitsOnOrder": 0,
        "ReorderLevel": 15,
        "Discontinued": false
    }
];

module.exports = { products }